services:

  backend:
    container_name: backend
    build:
      context: ./backend/cms
    ports:
      - 8000:8000
    volumes:
      - ./backend/cms:/app
      - backend-media:/mediafiles
    env_file:
      - ./backend/cms/.env
    command: >
      sh -c "
      set -xe;
      python manage.py collectstatic --noinput --clear && \
      python manage.py migrate && \
      gunicorn --bind 0.0.0.0:8000 cms.wsgi:application
      "
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:16.3
    env_file:
      - ./backend/cms/.env
    volumes:
      - db-data:/var/lib/postgresql/data
    
volumes:
  db-data:
  backend-media: