# Generated by Django 5.1.3 on 2024-11-12 14:42

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', 0), ('quote', 1), ('image', 2)], block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.BlockQuoteBlock', (), {'help_text': 'quote', 'max_length': 100}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False})}),
        ),
    ]
